name: HAOSHG680P

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y util-linux kpartx gzip xz-utils wget losetup parted e2fsprogs

      - name: Download Armbian
        run: |
          wget -O armbian.img.gz "https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bullseye_save_2025.08/Armbian_25.08.0_amlogic_s905x_bullseye_6.1.147_server_2025.08.01.img.gz"
          gunzip armbian.img.gz

      - name: Download HAOS
        run: |
          wget -O haos.img.xz "https://github.com/home-assistant/operating-system/releases/download/16.1/haos_generic-aarch64-16.1.img.xz"
          xz -d haos.img.xz

      - name: Mount Armbian and HAOS
        run: |
          mkdir -p armbian_boot armbian_root haos_boot haos_root
          
          # Setup loop device for Armbian
          sudo losetup -Pf armbian.img
          sudo partx -a /dev/loop0
          sudo mount /dev/loop0p1 armbian_boot
          sudo mount /dev/loop0p2 armbian_root
          
          # Setup loop device for HAOS
          sudo losetup -Pf haos.img
          sudo partx -a /dev/loop1
          sudo mount /dev/loop1p1 haos_boot
          sudo mount /dev/loop1p2 haos_root

      - name: Copy DTB and uEnv
        run: |
          sudo cp -v armbian_boot/uEnv.txt haos_boot/ || true
          sudo cp -v armbian_boot/dtb/amlogic/* haos_boot/dtb/amlogic/ || true

      - name: Unmount and cleanup
        run: |
          sudo umount armbian_boot || true
          sudo umount armbian_root || true
          sudo umount haos_boot || true
          sudo umount haos_root || true
          sudo losetup -D

      - name: Compress final HAOS image
        run: |
          gzip -c haos.img > haos_hg680p.img.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: haos_hg680p
          path: haos_hg680p.img.gz
